version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=${BACKEND_URL}
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
